### ISSUE TITLE
Uniform_combinatoric sampling

### ISSUE THREAD

**Issue by ahsanbutt95** [sweetpea-org/sweetpea-py#18]
Commented out impartial functionality of catering to kinarow contraints in uniform_combinatoric sampling to remove the need to create sat encoding and allow a faster solution. We should try to do this without requiring sat encoding.

**Comment by mflatt** [comment]
Rejection sampling was restored and completed for the combinatoric sampler. All SweetPea designs are now handled (although it will fail to produce a result if non-rejected samples are too sparse, of course).
