### ISSUE TITLE
exclude constraint not working

### ISSUE THREAD

**Issue by musslick** [sweetpea-org/sweetpea-py#25]
The exclude constraint appears to throw an error in the following code:

```
from sweetpea.primitives import Factor, DerivedLevel, WithinTrial
from sweetpea.constraints import minimum_trials, exclude
from sweetpea import fully_cross_block, synthesize_trials_non_uniform, print_experiments

# color and word factors

color      = Factor("color",  ["red", "blue", "green", "brown"])
word       = Factor("motion", ["red", "blue", "green", "brown"])

# congruency factor

def congruent(color, word):
    return color == word

def incongruent(color, word):
    return not congruent(color, word)

conLevel = DerivedLevel("con", WithinTrial(congruent,   [color, word]))
incLevel = DerivedLevel("inc", WithinTrial(incongruent,   [color, word]))

congruency = Factor("congruency", [
    conLevel,
    incLevel
])

# response factor

def response_up(color):
    return color == "red"
def response_down(color):
    return color == "blue"
def response_left(color):
    return color == "green"
def response_right(color):
    return color == "brown"

response = Factor("response", [
    DerivedLevel("up", WithinTrial(response_up,   [color])),
    DerivedLevel("down", WithinTrial(response_down,   [color])),
    DerivedLevel("left", WithinTrial(response_left,   [color])),
    DerivedLevel("right", WithinTrial(response_right,   [color])),
])

# constraints

min_20_trials = minimum_trials(20)
exclude_congruent_trials = [exclude(congruency, conLevel)]

constraints = [min_20_trials, exclude_congruent_trials]

# experiment

design       = [color, word, congruency, response]
crossing     = [color, word]
block        = fully_cross_block(design, crossing, constraints)

experiments  = synthesize_trials_non_uniform(block, 1)

print_experiments(block, experiments)
```

This is the error:

`Traceback (most recent call last):
  File "/Users/musslick/PycharmProjects/SweatPea/Examples/Manuscript_Example1_Stroop.py", line 55, in <module>
    block        = fully_cross_block(design, crossing, constraints)
  File "/Users/musslick/Documents/Cherkaev et al./tutorial code/sweetpea-py/sweetpea/__init__.py", line 32, in fully_cross_block
    all_constraints = __desugar_constraints(all_constraints) #expand the constraints into a form we can process.
  File "/Users/musslick/Documents/Cherkaev et al./tutorial code/sweetpea-py/sweetpea/__init__.py", line 59, in __desugar_constraints
    desugared_constraints.extend(c.desugar())
AttributeError: 'list' object has no attribute 'desugar'`

Perhaps this is an issue with my installation of SweetPea?  I'm wondering whether the error is reproducible. I pushed the code to example_programs/broken/Manuscript_Example1_Stroop.py

**Comment by mflatt** [comment]
In the code above, `exclude_congruent_trials` is a list  of one constraint, instead of being a constraint. It looks like we need to improve the error message here.

**Comment by mflatt** [comment]
The error message is now "ValueError: CrossBlock: expected list of Constraints for constraints, given [{'trials': 20}, [{'factor': Factor<congruency>, 'level': DerivedLevel<con>}]]".
