### ISSUE TITLE
"fully_cross_block" -> "block"

### ISSUE THREAD

**Issue by mflatt** [sweetpea-org/sweetpea-py#5]
This change is cosmetic, but involves updating examples, at least.

**Comment by oopzzozzo** [comment]
Should we merge the Block and FullyCrossBlock classes, or rename "Block" to some thing like "BaseBlock"?

**Comment by mflatt** [comment]
I'm not sure, but my best guess is to merge to `Block`.

Another possibility is that the `block` function might instantiate different kinds of block classes depending on the arguments, in which case we wouldn't want to merge the classes.
