### ISSUE TITLE
ExactlyKInARow (and other KInARow) prevents randomization

### ISSUE THREAD

**Issue by HuangHam** [sweetpea-org/sweetpea-py#50]
The code below is the example:

```
social = Factor(name="social", initial_levels=['nonsocial', 'social distribution', 'social reward'])
horizon = Factor(name="horizon", initial_levels=[10, 5]) 

# experiment
block_design     = [social, horizon]
block_crossing   = [social, horizon]
block      = fully_cross_block(design=block_design, crossing=block_crossing, constraints=[ExactlyKInARow(k=2,level=social)])
horizon_experiments = synthesize_trials_non_uniform(block=block, samples=1)
horizon_experiments
```
Running the code above should yield different outputs each time due to randomization of trial order. But it's not the case. If I remove the constraints, it works as expected. But I do need this constraint to make sure the social conditions are adjacent to each other. Would you please fix it? Somehow the constraints prevented the shuffling of the trial order.

**Comment by mflatt** [comment]
Unfortunately, this is a limitation of the tool that we use to solve constraints non-uniformly. In this very simple example, `synthesize_trials_uniform` manages to produce a result, and the result varies as it should. (It takes longer than I'm willing to wait if `k` and the number of levels in `horizon` is imcreased to 5.) For non-uniform sample, ... well, it's non-uniform in a specific way. :)

For non-uniform sampling, we just ask an underlying `cryptominisat5` tool to solve constraints. That tool accepts a `--random` argument, but that argument only controls certain searches. It seems to have no effect here (even for a larger variant of the example).

Without the constraint, you actually get uniform sampling using a different sampler, but that sampler only applies in simple cases.

Overall, the only way we have of dealing with this currently is to increase `samples=1` to get more than one sample. Then you can pick randomly from those samples. You'll be picking from the same N found solutions, though, even if there are more than N possible ones.

Improving this is an area of active research!

**Comment by mflatt** [comment]
There has been progress, because `RandomGen` can now work for this simple experiment, and `CMSGen` can work for this experiment and more complex variants. Also, the documentation is now more explicit about what you can expect from different strategies. So, I'll close this issue, although we will continue to work on strategies that can handle more kind of experiments.
