### ISSUE TITLE
rename 'level' in constraints KInARow(k, level) to 'factor'

### ISSUE THREAD

**Issue by younesStrittmatter** [sweetpea-org/sweetpea-py#52]
Maybe rename 'level' in the constraint KinARow(k, level) to 'factor' since the expected value is not a level but a factor

**Comment by mflatt** [comment]
Although a factor is allowed, it's intended as a shorthand for one constraint per level of the factor. Specifying a level (as a fatcor+level tuple) is the general form. This style of overloading was maybe a bad idea, but I think we probably shouldn't change the name unless making larger changes.

**Comment by younesStrittmatter** [comment]
Makes perfect sense. The naming is not problematic it just confused me the first time looking at it. Thank you for taking the time to answer and clear things up for me!
