### ISSUE TITLE
Bug in MultiCrossBlocks

### ISSUE THREAD

**Issue by younesStrittmatter** [sweetpea-org/sweetpea-py#57]
The following code produces a trial sequence that should be balanced in c but is not:

a = Factor("a", ["a1", "a2"])
b = Factor("b", ["b1", "b2"])
c = Factor("c", ["c1", "c2"])
design = [a, b, c]
crossing = [[c], [a,b]]
block=MultiCrossBlock(design,crossing,[])

I couldn't track down, under what circumstances the bug occures. I think, that it only occures if the crossings have different lengths (but it does not always occure in that case. for example:

crossing = [[a,b],[c]] 

seems to work

**Comment by mflatt** [comment]
Thanks for the report! I've pushed a repair as fcc66ea5c5a0614756a3ea1b44e08b8c389a4de6 and updated the package on pip. The constraint setup wasn't right at all for crossings of different sizes.
